### ISSUE TITLE
Study options for inja environment customization

### ISSUE THREAD

**Issue by indiosmo** [sporacid/spore-codegen#30]
Think about options on how to allow the user to add their own callbacks to the inja environment.

While this might not be possible via the main application, the user can still use `spore-codegen` as a library and write their own application.

This is generalizable for the parser and converter as well.
The library design already allows for this by providing base classes `ast_parser`, `ast_converter` and `codegen_renderer`, so it's just a matter of allowing the user to provide their own.

We could add arguments to `run_codegen()` where the user can inject their own implementations or inject some other way.

**Comment by sporacid** [comment]
Yes I thought about that, I was thinking of maybe adding a scripting runtime to provide callbacks dynamically. We could definitely change how the CMake executable is built in order to have a library, but I think overriding `ast_parser`, `ast_converter` and `codegen_renderer` has limited use in the end. I think the project can provide standard implementations for these, and if some other project want to build another executable from the library, they'll be able to do so. What do you think?

**Comment by sporacid** [comment]
I've changed the CMake scripts to build an `INTERFACE` library and linking the binary unto it. https://github.com/sporacid/spore-codegen/pull/31

**Comment by sporacid** [comment]
As for scripting, I thought maybe this would do the job: https://chaiscript.com/index.html

**Comment by indiosmo** [comment]
I'm not particularly familiar with scripting so I really need to play around some more before giving an opinion.

I hear as far as integrating with c++, chaiscript is the easiest as it was made specifically for c++, so that could be a good choice.
